In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Review

In [5]:
cones = Table.read_table('cones.csv')
cones

FileNotFoundError: [Errno 2] No such file or directory: 'cones.csv'

### Discussion Q1

In [ ]:
# Find percentage of rows that match the condition color pink

In [5]:
pink_cones = cones.where('Color', 'pink')
pink_cones

NameError: name 'cones' is not defined

In [ ]:
pink_cones.num_rows / cones.num_rows * 100

### Discussion Question 2

What does the following evaluate to

```
x = 5
y = 7

max(x, y)
min(x-y, x+y, x*y, x/y)
round(x/y)
x * 2.5
y + '5'

```

In [6]:
x = 5
y = 7

In [7]:
# Case 1
max(x, y)

7

In [8]:
# Case 2
min(x-y, x+y, x*y, x/y)

-2

In [9]:
# Case 3
round(x/y)

1

In [10]:
# Case 4
x * 2.5

12.5

In [11]:
# Case 5
y + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## Numbers ##

In [12]:
30

30

In [13]:
3 * 30 # int

90

In [14]:
10 / 3 # float

3.3333333333333335

In [15]:
3 / 3

1.0

In [16]:
10 ** 3 # 10 * 10 * 10 

1000

In [17]:
10 ** 0.5 # float

3.1622776601683795

In [18]:
12345678 ** 890

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [ ]:
75892745.215489247589274985712

In [ ]:
75892745.215489247589274985712 - 75892745.21548925

In [ ]:
10 / 5

In [ ]:
int(10 / 5)

In [ ]:
16 / 30

In [ ]:
round(16 / 30), int(16 / 30)

In [ ]:
round(6/10), int(6/10)

In [ ]:
float(3)

In [ ]:
1e-6

In [ ]:
1e-56

## Strings ##

In [ ]:
'Flavor'

In [ ]:
"Flavor"

In [ ]:
'"This is a quote from Jeremy"'

In [ ]:
Flavor

In [ ]:
'Don't do this'

In [ ]:
'straw' + 'berry'

In [ ]:
'Chris' + ' ' + 'is' + ' ' + 'cool'

In [ ]:
'ha' * 1000

In [ ]:
'HA' * 1.5

In [ ]:
'ha' + 10

In [ ]:
5 + int('5')

In [ ]:
'yelp review:' + str(10)

In [ ]:
int('3.0')

In [ ]:
int(float('3.0'))

## Types ##

In [ ]:
type(10)

In [ ]:
type(10.5)

In [ ]:
type('apple juice')

In [69]:
Kanu = 'kevin'
Kevin = 'kevin'
Ciara = 'ciara'

In [ ]:
Kanu == Kevin

In [ ]:
Ciara == Kevin

In [ ]:
type(Ciara == Kevin)

In [ ]:
abs(-5)

In [ ]:
type(abs)

## Arrays ##

In [19]:
my_array = make_array(1, 2, 3)

In [20]:
my_array

array([1, 2, 3])

In [21]:
len(my_array)

3

In [22]:
my_array + 2

array([3, 4, 5])

In [23]:
my_array * 2

array([2, 4, 6])

In [24]:
my_array = my_array ** 2

In [25]:
my_array

array([1, 4, 9])

In [26]:
my_array_2 = make_array(-1, -2, -1)

In [27]:
my_array_2 + my_array

array([0, 2, 8])

In [28]:
my_array_3 = make_array(1,2,3,4)

In [29]:
my_array_3

array([1, 2, 3, 4])

In [30]:
my_array + my_array_3

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [31]:
names_array = make_array('Andrew', "Conan", 'Jonathan')
names_array

array(['Andrew', 'Conan', 'Jonathan'],
      dtype='<U8')

In [32]:
names_array.item(0)

'Andrew'

In [33]:
names_array.item(1)

'Conan'

In [34]:
names_array.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

## Columns of Tables are Arrays ##

In [95]:
nba = Table.read_table('nba_salaries.csv').relabeled(4, 'SALARY')
warriors = nba.where('team', 'Golden State Warriors')

In [ ]:
warriors

In [ ]:
type(warriors.select('SALARY'))
# Returns a column in a table format

In [101]:
SALARY = warriors.column('SALARY')

In [103]:
# np.average(warriors.select('SALARY'))
# can't call numpy function on tables

In [ ]:
np.average(warriors.column('SALARY'))

In [ ]:
np.average(warriors.where('name', 'Chris Mills').column('SALARY'))

In [ ]:
warriors.where('name', 'Chris Mills').column('SALARY').item(0)

## Ranges ##

In [ ]:
np.arange(10) # make_array(0,1,2,3,4,5,6,7,8,9)
# np.arange(END)

In [ ]:
np.arange(1, 10)
# np.arange(START, END)

In [ ]:
np.arange(1, 10, 2)
# np.arange(START, END, STEP)

In [ ]:
np.arange(1, 11)

In [ ]:
np.arange(1, 10.1)

## Reading a Table from a File  ##

In [ ]:
du_bois = Table.read_table('du_bois.csv')
du_bois

## Discussion Question

Use the table functions we learned this week to find the income bracket (“class”) that spent the highest percentage of their income on rent.

In [ ]:
du_bois.sort('RENT', descending = True).column('CLASS').item(0)

# Lecture 4b: Census

## Census ##

In [ ]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

In [ ]:
partial = full.select('SEX', 'AGE', 'POPESTIMATE2014', 'POPESTIMATE2019')
partial.show(5)

In [ ]:
us_pop = partial.relabeled(2, '2014').relabeled(3, '2019')
us_pop.show(5)

In [ ]:
us_pop.where('AGE', are.above_or_equal_to(100))

In [ ]:
us_pop.where('AGE', >= 100)

## 2019 Sex Ratios ##

In [ ]:
us_pop_2019 = us_pop.drop('2014')
us_pop_2019.show(3)

In [ ]:
all_ages = us_pop_2019.where('AGE', are.equal_to(999))
all_ages

In [ ]:
infants = us_pop_2019.where('AGE', are.equal_to(0))
infants

In [ ]:
females_all_rows = us_pop_2019.where('SEX', are.equal_to(2))
females = females_all_rows.where('AGE', are.not_equal_to(999))
females.show(3)

In [ ]:
males_all_rows = us_pop_2019.where('SEX', are.equal_to(1))
males = males_all_rows.where('AGE', are.not_equal_to(999))
males.show(3)

In [ ]:
f_to_m_ratios = females.column(2) / males.column(2)

ratios = Table().with_columns(
    'Age', females.column('AGE'),
    'F:M Ratio', f_to_m_ratios
)

ratios

In [ ]:
ratios.sort('Age', descending=True)

## Line Plot ##

In [ ]:
ratios.plot('Age', 'F:M Ratio')

## Optional: Adding a Title to a Plot ##

In [ ]:
ratios.plot('Age', 'F:M Ratio')
plots.title('2019 US Population');

## Optional: set_format and PercentFormatter ##

In [ ]:
infants

In [ ]:
total_infants_2019 = infants.column('2019').item(0)
total_infants_2019

In [ ]:
infants = infants.with_column(
    'Proportion', infants.column('2019')/total_infants_2019
)
infants

In [ ]:
# A more easily readable display
# Displays proportions as percents
infants.set_format('Proportion', PercentFormatter)

In [ ]:
# Once the format is set, it remains.
infants